CREATE TABLE IF NOT EXISTS conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    memory_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    viewer_id VARCHAR(50) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_app_user_login_id
        UNIQUE (login_id),
    CONSTRAINT uq_app_user_viewer_id
        UNIQUE (viewer_id),
    CONSTRAINT chk_app_user_viewer_id
        CHECK (viewer_id IN ('Moon', 'Sun'))
);

CREATE TABLE IF NOT EXISTS message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    author VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    display_time VARCHAR(10) NOT NULL,
    sequence INT NOT NULL,
    CONSTRAINT fk_message_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES conversation(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_message_sequence
        UNIQUE (conversation_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_conversation_memory_date
    ON conversation (memory_date DESC);

CREATE INDEX IF NOT EXISTS idx_app_user_enabled
    ON app_user (enabled);

CREATE INDEX IF NOT EXISTS idx_message_conversation_id
    ON message (conversation_id);
