CREATE TABLE IF NOT EXISTS conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    memory_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    author VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    display_time VARCHAR(10) NOT NULL,
    sequence INT NOT NULL,
    CONSTRAINT fk_message_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES conversation(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_message_sequence
        UNIQUE (conversation_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_conversation_memory_date
    ON conversation (memory_date DESC);

CREATE INDEX IF NOT EXISTS idx_message_conversation_id
    ON message (conversation_id);
